### PR TITLE
Cleaned up the SDK

### PR DESCRIPTION
**Pull request by dragonmantank**
This PR has a few fixes that are introduced:

* A few bug fixes relating to some typos in the code
* Changed v3 over to PSR-4 and namespaces, to bring this in-line with v2
* Fixed and broke up the example code
* Unit tests for everything that doesn't directly rely on IronCore, since it uses cURL and can't be mocked properly

### CODE REVIEW

**Comment by thousandsofthem** [comment]
Hey @dragonmantank ! Thanks for the effort. 
Did you check this: https://github.com/iron-io/iron_mq_php#branches ?
There are v4 branch exactly for this purpose

**Comment by dragonmantank** [comment]
Nope, didn't realize that was what that was for. We were directed to use the v3 of the API since we are using hud-e, and were directed to that SDK. I had also noticed that http://dev.iron.io/mq/3/libraries/ is pointing to the v3 branch as well. 

Is the v4 branch just a cleanup of v3 (no client-facing programming API changes), or are there any changes between them? If not, I'll move the unit tests and examples over to a PR for v4.

**Comment by thousandsofthem** [comment]
@dragonmantank v4 is cleaned up copy if v3, yes. None or almost none changes made except moving/separating files, adding namespaces, things like that

**Comment by dragonmantank** [comment]
I moved this to https://github.com/iron-io/iron_mq_php/pull/63 and against v4

**Pull request closed without merging**
